/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package AreasT;

import Clases.Diseno;
import java.io.IOException;
import java.security.GeneralSecurityException;
import java.util.logging.Level;
import java.util.logging.Logger;

import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Luciifer
 */
public class AreaTexto1 extends javax.swing.JFrame {

    /**
     * Creates new form AreaTexto1
     */

    public  DefaultListModel lista1=new DefaultListModel();
        Clases.Funciones fn =new Clases.Funciones();
           
            Clases.Docentes dc =new Clases.Docentes();
           
    
    public AreaTexto1() {
      
            initComponents();
        
     

            
            
       
 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        Texto1 = new javax.swing.JList<>();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("6 AM ");

        Texto1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        Texto1.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                Texto1ValueChanged(evt);
            }
        });
        jScrollPane3.setViewportView(Texto1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 514, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 171, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void Texto1ValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_Texto1ValueChanged
        try {
            
            Clases.TextosTabla tx=new Clases.TextosTabla();
          //  dc.Spread(Clases.Diseno.Link.getText());
            //  Clases.Diseno.Link.getText();
          
            
                       switch(Texto1.getSelectedIndex()){
                case 2:
                    System.out.print(fn.Buscador("B8"));
                    Clases.TextosTabla.Textos.setText(" ");
                    String uu=Texto1.getSelectedValue(); 
                    
                    
                    if(JOptionPane.showConfirmDialog(null,uu)==1 ||JOptionPane.showConfirmDialog(null,uu)==2){
                        break;
                    }else{
                      
                        switch(Clases.Diseno.ComboB.getSelectedIndex()){
                            case 1:
                                 
                                tx.setVisible(true);
                                Clases.TextosTabla.Textos.append(uu+"\n");
                                Clases.TextosTabla.Textos.append(dc.Datos(8, 15,"TUTORIAS-INTRO!", "A", "F")+"\n");
                                Clases.Docentes.ls2.clear();
                                break;
                            case 2:
                                tx.setVisible(true);
                                Clases.TextosTabla.Textos.append(uu+"\n");
                                Clases.TextosTabla.Textos.append(dc.Datos(8, 15,"ING A1!", "A", "F")+"\n");
                                Clases.Docentes.ls2.clear();
                                break;
                            case 3:
                                tx.setVisible(true);
                                Clases.TextosTabla.Textos.append(uu+"\n");
                                Clases.TextosTabla.Textos.append(dc.Datos(8, 15,"ING A2!", "A", "F")+"\n");
                                Clases.Docentes.ls2.clear();
                                break;
                            case 4:
                                tx.setVisible(true);
                                Clases.TextosTabla.Textos.append(uu+"\n");
                                Clases.TextosTabla.Textos.append(dc.Datos(8, 15,"ING B1!", "A", "F")+"\n");
                                Clases.Docentes.ls2.clear();
                                break;
                            case 5:
                                tx.setVisible(true);
                                Clases.TextosTabla.Textos.append(uu+"\n");
                                Clases.TextosTabla.Textos.append(dc.Datos(8, 15,"ING B2!", "A", "F")+"\n");
                                Clases.Docentes.ls2.clear();
                                break;
                            case 6:
                                tx.setVisible(true);
                                Clases.TextosTabla.Textos.append(uu+"\n");
                                Clases.TextosTabla.Textos.append(dc.Datos(8, 15,"ING C1!", "A", "F")+"\n");
                                Clases.Docentes.ls2.clear();
                                break;
                            case 7:
                                tx.setVisible(true);
                                Clases.TextosTabla.Textos.append(uu+"\n");
                                Clases.TextosTabla.Textos.append(dc.Datos(8, 15,"FRANCES!", "A", "F")+"\n");
                                Clases.Docentes.ls2.clear();;
                                break;
                            case 8:
                                tx.setVisible(true);
                                Clases.TextosTabla.Textos.append(uu+"\n");
                                Clases.TextosTabla.Textos.append(dc.Datos(8, 15,"CLUBES!", "A", "F")+"\n");
                               Clases.Docentes.ls2.clear();
                                break;
                        }
                        
                    }
                    break;
            }                    
        } catch (GeneralSecurityException ex) {
            Logger.getLogger(AreaTexto1.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(AreaTexto1.class.getName()).log(Level.SEVERE, null, ex);
        }
  
    }//GEN-LAST:event_Texto1ValueChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AreaTexto1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AreaTexto1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AreaTexto1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AreaTexto1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AreaTexto1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JList<String> Texto1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
